### ISSUE TITLE
.Net Core port

### ISSUE THREAD

**Issue by NimeshDhruve** [zoranmax/GoogleDataTableLib#1]
Thanks for the library. It works like a charm. I am wondering would it possible to target project to .Net Standard 2 for this library?

Currently it works in .Net Core project but I get annoying warning (pasted below). I saw your note on the home page about why you are basing it .Net 3.5 so I am certainly little hesitant to put this request but I thought it is worth a try.

This may help:
https://docs.microsoft.com/en-us/nuget/create-packages/supporting-multiple-target-frameworks

Thanks again for the library :)
```

Warning	NU1701	Package 'Google.DataTable.Net.Wrapper 3.1.2' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may not be fully compatible with your project.	TRS.Web	D:\SVN\projects\TestResultServer\trunk\TRS.Web\TRS.Web.csproj	1	

```

**Comment by zoranmax** [comment]
Hi,
First of all, thanks for your comment. :)

This library indeed was written with the very basic set of needs and for one of the projects I was working on. You are however right, it need to be refreshed.

I will work on this and convert the project to .NET Core. I have just to figure out what are the standard ways of supporting two frameworks at once in the same source code, and to look at the .NET Standard 2.

I cannot give you a timeline but as soon as I have some free time will start working on it.

Regards,
Zoran
ps: feel free to contribute to it if you wish! :)

**Comment by zoranmax** [comment]
A new version of the library covering .NET Standards 2.0 is available on nuget as a pre-release

https://www.nuget.org/packages/Google.DataTable.Net.Wrapper/4.0.0-rc1

**Comment by jackfoxy** [comment]
@zoranmax  We finally have a netstandard2.0 version of XPlot, consuming 4.0.0-rc1, and it does work in a Windows environment. I don't use any non-Windows environments, so I cannot more.
