### ISSUE TITLE
GetFormattedValue in Cell.cs subtracts 1 from the month

### ISSUE THREAD

**Issue by reshriver** [zoranmax/GoogleDataTableLib#14]
Anytime a Date or DateTime ColumnType is passed to the GetFormattedValue method in the Cell class the Month part of the date is reduced by 1.  So February 27, 2023 gets converted to January 27, 2023.  I don't understand why you want to subtract 1 from the month.  Otherwise everything else is working great.

**Comment by reshriver** [comment]
I did some additional research and found that this is not a bug but was done because JavaScript uses a zero based month when creating dates.  So all is good.  Thank you for creating this project.  It's works great!

**Comment by zoranmax** [comment]
Thank you very much for using the tool!
